apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nuwhh99rm-python 
  janus-idp.io/tekton: nuwhh99rm-python
  backstage.io/kubernetes-id: nuwhh99rm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nuwhh99rm-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml