apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nuwhh99rm-python
  janus-idp.io/tekton: nuwhh99rm-python
  backstage.io/kubernetes-id: nuwhh99rm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nuwhh99rm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
