apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nuwhh99rm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nuwhh99rm-python 
  name: nuwhh99rm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nuwhh99rm-python 
